apiVersion: v1
kind: Service
metadata:
  name: finsights-svc
spec:
  type: NodePort
  selector:
    app: finsights
  ports:
    - name: http
      port: 80
      targetPort: 8084
      nodePort: 30080
